# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'packetDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PacketDetails(object):
    def setupUi(self, Form):
        Form.setObjectName("PacketDetails")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.detailTreeWidget = QtWidgets.QTreeWidget(Form)
        self.detailTreeWidget.setObjectName("detailTreeWidget")
        self.detailTreeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.detailTreeWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
