# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'packetDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PacketDetails(object):
    def setupUi(self, packetWindow):
        packetWindow.setObjectName("packetWindow")
        packetWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(packetWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        packetWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(packetWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        packetWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(packetWindow)
        self.statusbar.setObjectName("statusbar")
        packetWindow.setStatusBar(self.statusbar)

        self.retranslateUi(packetWindow)
        QtCore.QMetaObject.connectSlotsByName(packetWindow)

    def retranslateUi(self, packetWindow):
        _translate = QtCore.QCoreApplication.translate
        packetWindow.setWindowTitle(_translate("packetWindow", "packetWindow"))
