---
  tcp_scan_detect_threshold: 100
  dos_detect_threshold: 100
  icmp_flood_detect_threshold: 100
  http_flood_detect_threshold: 100
  dns_flood_detect_threshold: 100
  udp_flood_detect_threshold: 100
  