name: Push_tests

on:
  pull_request:
    branches: [ "main", "dev", "continuous-integration" ]


jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.8'
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scapy
          pip install PyQt5
          pip install pandas
          pip install matplotlib
          pip install networkx
          pip install libpcap
      
      - name: Run Tests
        run: |
          cd src
          python -m unittest Packet_Capture_tests.py
          python -m unittest attack_analysis_tests.py
          
